//! Emit-time DETECTION of non-composable cardinality-1 tile ids.
//!
//! # What this is (and firmly is not)
//!
//! Alizarin GENERATES composable ids for cardinality-1 tiles: a tile's id is
//! `uuid5(TILE_NS, "{scope}/{nodegroup_id}")`, where the scope is its parent
//! tile if it has one and its resource otherwise (see
//! `alizarin_core::graph::canonical_tile_id`). That is what lets a layer built
//! in ISOLATION compute — and therefore override — the id of a cardinality-1
//! tile it has never seen.
//!
//! Tiles that came out of an ARCHES EXPORT carry ids Arches minted at random.
//! They are not composable, and this module DOES NOT REWRITE THEM. There is no
//! canonicalisation pass, here or anywhere: rewriting ids at emit time would
//! silently re-identify tiles that other layers, and Arches itself, already
//! reference. We DETECT the condition and refuse to emit an artifact whose
//! layers cannot compose.
//!
//! # The check
//!
//! The invariant a cardinality-1 nodegroup must satisfy is ONE TILE PER PARENT
//! INSTANCE — not one tile per resource. So tiles are grouped by
//! **(scope, nodegroup_id)**, scope being `parenttile_id` if present, else the
//! resource id. Each group must hold exactly one tile.
//!
//! # THE FALSE-POSITIVE TRAP — do not "simplify" this to (resource, nodegroup)
//!
//! A cardinality-1 nodegroup NESTED UNDER A CARDINALITY-N PARENT legitimately
//! has MANY tiles per resource — one per parent instance, each with a different
//! id. That is correct, ordinary data. Grouping by (resource, nodegroup) would
//! lump all of them together and reject it. Grouping by (scope, nodegroup)
//! separates them by parent instance, which is exactly the invariant. There is
//! a test named for this; keep it passing.

use std::collections::HashMap;

use alizarin_core::{StaticGraph, StaticResource};

/// A cardinality-1 nodegroup holding more than one tile in the same scope.
///
/// The rule is on the COUNT — exactly one tile per (scope, nodegroup) — and
/// there are two ways to break it, which mean different things and get
/// different messages. Checking only for *differing* ids (as this did) misses
/// the second entirely.
#[derive(Debug)]
pub struct NonComposableTileIds {
    pub resource_id: String,
    pub nodegroup_id: String,
    pub count: usize,
    pub first_id: String,
    /// The id of the second tile in the group. `None` when it is the SAME id as
    /// `first_id` — which is the duplicate-instance case, not an id conflict.
    pub second_id: Option<String>,
}

impl std::fmt::Display for NonComposableTileIds {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self.second_id {
            // DIFFERENT ids: the ids were not derived, so they cannot be
            // recomputed by a layer that has never seen this tile.
            Some(second_id) => write!(
                f,
                "resource {}: cardinality-1 nodegroup {} has {} tiles under the same \
                 parent with different ids ({}, {}) — these should be a single tile. \
                 Tiles generated by Arches carry random ids and are not composable; \
                 only alizarin-generated tiles have derivable cardinality-1 ids. \
                 Layers may be incomposable.",
                self.resource_id, self.nodegroup_id, self.count, self.first_id, second_id
            ),
            // SAME id: the ids ARE derived — correctly, and identically, because
            // a cardinality-1 nodegroup has exactly one canonical id per scope.
            // The data is what is wrong: several tile instances were minted where
            // the schema permits one, so they all collide on that one id and all
            // but one would be silently lost. Emitting this would publish an
            // artifact that quietly drops data.
            None => write!(
                f,
                "resource {}: cardinality-1 nodegroup {} has {} tile instances under \
                 the same parent, all sharing the canonical id {} — MALFORMED DATA. \
                 A cardinality-1 nodegroup admits exactly one tile per parent \
                 instance, so every one of these derives the same id and they \
                 collide: all but one would be lost. The usual cause is a \
                 cardinality-1 nodegroup fed an ARRAY of objects rather than a \
                 single object. Fix the input, or declare the nodegroup \
                 cardinality-n.",
                self.resource_id, self.nodegroup_id, self.count, self.first_id
            ),
        }
    }
}

impl std::error::Error for NonComposableTileIds {}

/// Verify that every cardinality-1 nodegroup in `resource` holds exactly one
/// tile per parent instance.
///
/// Nodegroups whose cardinality the graph does not state are SKIPPED: without a
/// stated cardinality we cannot know the tile should be unique, and alizarin
/// does not generate a canonical id for them either (the two sides agree on
/// what they do not know).
pub(crate) fn validate_composable_tile_ids(
    resource: &StaticResource,
    graph: &StaticGraph,
) -> Result<(), NonComposableTileIds> {
    let Some(tiles) = resource.tiles.as_ref() else {
        return Ok(());
    };
    let resource_id = &resource.resourceinstance.resourceinstanceid;

    // (scope, nodegroup) -> the first tile id seen in that group.
    // Scope is the PARENT INSTANCE where there is one — see the false-positive
    // trap in the module docs.
    let mut seen: HashMap<(&str, &str), (&str, usize)> = HashMap::new();

    for tile in tiles {
        let cardinality_one = graph
            .get_nodegroup_by_id(&tile.nodegroup_id)
            .and_then(|ng| ng.cardinality.as_deref())
            .map(|c| c != "n")
            .unwrap_or(false);
        if !cardinality_one {
            continue;
        }

        let scope = match tile.parenttile_id.as_deref() {
            Some(parent) if !parent.is_empty() => parent,
            _ => resource_id.as_str(),
        };
        let Some(tile_id) = tile.tileid.as_deref() else {
            continue;
        };

        match seen.get_mut(&(scope, tile.nodegroup_id.as_str())) {
            None => {
                seen.insert((scope, tile.nodegroup_id.as_str()), (tile_id, 1));
            }
            Some((first_id, count)) => {
                *count += 1;
                // THE RULE IS ON THE COUNT: exactly one tile per (scope,
                // nodegroup). A second tile in the group is an error either way
                // — what differs is WHICH error.
                //
                // Same id twice used to be waved through as "a duplicate, but
                // still addressable". It is not benign: a cardinality-1
                // nodegroup fed an array of two objects produces exactly this,
                // and since both derive the same canonical id they collide, so
                // one silently overwrites the other. Accepting it means emitting
                // an artifact that has quietly lost data.
                return Err(NonComposableTileIds {
                    resource_id: resource_id.clone(),
                    nodegroup_id: tile.nodegroup_id.clone(),
                    count: *count,
                    first_id: (*first_id).to_string(),
                    second_id: (*first_id != tile_id).then(|| tile_id.to_string()),
                });
            }
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use alizarin_core::{StaticResource, StaticTile};

    /// root -> `solo` (cardinality 1)
    ///      -> `many` (cardinality N)
    ///           -> `nested` (cardinality 1, one tile PER `many` instance)
    fn graph() -> StaticGraph {
        let json = serde_json::json!({
            "graphid": "g1",
            "name": {"en": "G"},
            "root": {
                "nodeid": "root", "name": "Root", "alias": "root",
                "datatype": "semantic", "graph_id": "g1", "istopnode": true
            },
            "nodes": [
                { "nodeid": "root", "name": "Root", "alias": "root",
                  "datatype": "semantic", "graph_id": "g1", "istopnode": true },
                { "nodeid": "solo-ng", "name": "Solo", "alias": "solo",
                  "datatype": "string", "nodegroup_id": "solo-ng", "graph_id": "g1" },
                { "nodeid": "many-ng", "name": "Many", "alias": "many",
                  "datatype": "semantic", "nodegroup_id": "many-ng", "graph_id": "g1" },
                { "nodeid": "nested-ng", "name": "Nested", "alias": "nested",
                  "datatype": "string", "nodegroup_id": "nested-ng", "graph_id": "g1" }
            ],
            "nodegroups": [
                { "nodegroupid": "solo-ng", "cardinality": "1" },
                { "nodegroupid": "many-ng", "cardinality": "n" },
                { "nodegroupid": "nested-ng", "cardinality": "1",
                  "parentnodegroup_id": "many-ng" }
            ],
            "edges": [
                { "domainnode_id": "root", "rangenode_id": "solo-ng" },
                { "domainnode_id": "root", "rangenode_id": "many-ng" },
                { "domainnode_id": "many-ng", "rangenode_id": "nested-ng" }
            ]
        });
        let mut graph: StaticGraph = serde_json::from_value(json).expect("graph");
        graph.build_indices();
        graph
    }

    fn tile(id: &str, nodegroup: &str, parent: Option<&str>) -> StaticTile {
        let mut t = StaticTile::new_empty(nodegroup.to_string());
        t.tileid = Some(id.to_string());
        t.resourceinstance_id = "res-1".to_string();
        t.parenttile_id = parent.map(str::to_string);
        t
    }

    fn resource(tiles: Vec<StaticTile>) -> StaticResource {
        let mut r: StaticResource = serde_json::from_value(serde_json::json!({
            "resourceinstance": {
                "descriptors": {},
                "graph_id": "g1",
                "name": "Resource One",
                "resourceinstanceid": "res-1"
            }
        }))
        .expect("resource");
        r.tiles = Some(tiles);
        r
    }

    #[test]
    fn accepts_one_tile_per_cardinality_one_nodegroup() {
        let r = resource(vec![tile("t-solo", "solo-ng", None)]);
        assert!(validate_composable_tile_ids(&r, &graph()).is_ok());
    }

    /// THE FALSE-POSITIVE GUARD. A cardinality-1 nodegroup under a
    /// cardinality-N parent has one tile PER PARENT INSTANCE — many tiles per
    /// resource, all with different ids. This is valid and must NOT error.
    #[test]
    fn accepts_cardinality_one_nested_under_cardinality_n_parent() {
        let r = resource(vec![
            tile("t-solo", "solo-ng", None),
            tile("t-many-1", "many-ng", None),
            tile("t-many-2", "many-ng", None),
            tile("t-many-3", "many-ng", None),
            // One nested tile per parent instance: three tiles, three ids, one
            // cardinality-1 nodegroup, one resource. Entirely legitimate.
            tile("t-nested-1", "nested-ng", Some("t-many-1")),
            tile("t-nested-2", "nested-ng", Some("t-many-2")),
            tile("t-nested-3", "nested-ng", Some("t-many-3")),
        ]);
        assert!(
            validate_composable_tile_ids(&r, &graph()).is_ok(),
            "grouping by (resource, nodegroup) instead of (scope, nodegroup) \
             would have falsely rejected this"
        );
    }

    #[test]
    fn rejects_two_root_tiles_of_one_cardinality_one_nodegroup() {
        let r = resource(vec![
            tile("id-aaa", "solo-ng", None),
            tile("id-bbb", "solo-ng", None),
        ]);
        let err = validate_composable_tile_ids(&r, &graph()).expect_err("must reject");
        let msg = err.to_string();

        assert!(msg.contains("res-1") && msg.contains("solo-ng"));
        assert!(msg.contains("id-aaa") && msg.contains("id-bbb"));
        assert!(
            msg.contains("Arches") && msg.contains("not composable"),
            "the message must name the likely cause. Got: {msg}"
        );
    }

    /// THE COUNT RULE. Two tiles in one scope sharing the SAME canonical id.
    ///
    /// This used to pass silently: the check only fired on DIFFERING ids, so a
    /// cardinality-1 nodegroup fed an array of two objects — which mints one
    /// tile per object, each deriving the same canonical id — sailed through.
    /// Both tiles collide on that id, so one is silently lost. Malformed data,
    /// accepted, and the loss invisible in the artifact.
    #[test]
    fn rejects_duplicate_instances_sharing_one_canonical_id() {
        let r = resource(vec![
            tile("id-same", "solo-ng", None),
            tile("id-same", "solo-ng", None),
        ]);
        let err = validate_composable_tile_ids(&r, &graph()).expect_err(
            "two tiles in one cardinality-1 scope must be rejected on COUNT, even \
             when their ids agree",
        );
        let msg = err.to_string();

        assert!(msg.contains("res-1") && msg.contains("solo-ng") && msg.contains("id-same"));
        // The message must be the MALFORMED-DATA one, not the incomposable-ids
        // one: the ids here are perfectly derivable, the data is wrong.
        assert!(
            msg.contains("MALFORMED DATA") && msg.contains("ARRAY"),
            "must name the cause (a cardinality-1 nodegroup fed an array). Got: {msg}"
        );
        assert!(
            !msg.contains("Arches"),
            "these ids ARE composable — blaming Arches misdiagnoses it: {msg}"
        );
        assert_eq!(
            err.second_id, None,
            "same id: there is no second id to name"
        );
    }

    /// Two tiles of the same nested cardinality-1 nodegroup under the SAME
    /// parent instance: unlike the case above, this one IS a violation.
    #[test]
    fn rejects_two_nested_tiles_under_the_same_parent_instance() {
        let r = resource(vec![
            tile("t-many-1", "many-ng", None),
            tile("id-aaa", "nested-ng", Some("t-many-1")),
            tile("id-bbb", "nested-ng", Some("t-many-1")),
        ]);
        let err = validate_composable_tile_ids(&r, &graph()).expect_err("must reject");
        assert!(err.to_string().contains("nested-ng"));
    }

    #[test]
    fn ignores_cardinality_n_nodegroups_entirely() {
        // Many tiles, many ids, one nodegroup, one resource: the whole point of
        // cardinality N.
        let r = resource(vec![
            tile("m1", "many-ng", None),
            tile("m2", "many-ng", None),
            tile("m3", "many-ng", None),
        ]);
        assert!(validate_composable_tile_ids(&r, &graph()).is_ok());
    }
}
